#!/bin/sh

bundle exec middleman build --verbose
git branch -D gh-pages
git checkout --orphan gh-pages
git rm -rf .
git checkout master CNAME
mv build/* ./
rm -r build
git add --all
git commit --all -m 'website'
git push --set-upstream origin gh-pages -f
git checkout master
